apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client # Used in client-cluster-ip-service.yaml
    spec:
      containers:
      - name: client
        image: pgsoncada/client-image
        ports:
        - containerPort: 3000
